services:
  - type: web
    name: ecodrop-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REPORT_TARGET_EMAIL
        sync: false
      - key: REPORT_FROM_EMAIL
        sync: false
      - key: RESEND_API_KEY
        sync: false
    autoDeploy: true
